/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package javaapplication1;

import com.formdev.flatlaf.intellijthemes.FlatVuesionIJTheme;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author mystica fumi
 */
public class Admin_View extends javax.swing.JFrame {

    /**
     * Creates new form Admin_View
     */
    public Admin_View() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel6 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        dashboardB = new javax.swing.JLabel();
        studentListB = new javax.swing.JLabel();
        departmentB = new javax.swing.JLabel();
        eventsB = new javax.swing.JLabel();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        BlankP = new javax.swing.JPanel();
        dashboardP = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        studentListP = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        departmentP = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        ccsB = new javax.swing.JLabel();
        cbaaB = new javax.swing.JLabel();
        claB = new javax.swing.JLabel();
        ccjeB = new javax.swing.JLabel();
        cnmB = new javax.swing.JLabel();
        tetdB = new javax.swing.JLabel();
        cedB = new javax.swing.JLabel();
        hsB = new javax.swing.JLabel();
        jLayeredPane2 = new javax.swing.JLayeredPane();
        blank2P = new javax.swing.JPanel();
        ccsP = new javax.swing.JPanel();
        jLabel33 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        cbaaP = new javax.swing.JPanel();
        jLabel34 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable4 = new javax.swing.JTable();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        claP = new javax.swing.JPanel();
        jLabel35 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTable5 = new javax.swing.JTable();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        ccjeP = new javax.swing.JPanel();
        jLabel46 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTable6 = new javax.swing.JTable();
        jLabel47 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        cnmP = new javax.swing.JPanel();
        jLabel50 = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        jTable7 = new javax.swing.JTable();
        jLabel51 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();
        tetdP = new javax.swing.JPanel();
        jLabel54 = new javax.swing.JLabel();
        jScrollPane8 = new javax.swing.JScrollPane();
        jTable8 = new javax.swing.JTable();
        jLabel55 = new javax.swing.JLabel();
        jLabel56 = new javax.swing.JLabel();
        jLabel57 = new javax.swing.JLabel();
        cedP = new javax.swing.JPanel();
        jLabel58 = new javax.swing.JLabel();
        jScrollPane9 = new javax.swing.JScrollPane();
        jTable9 = new javax.swing.JTable();
        jLabel59 = new javax.swing.JLabel();
        jLabel60 = new javax.swing.JLabel();
        jLabel61 = new javax.swing.JLabel();
        hsP = new javax.swing.JPanel();
        jLabel62 = new javax.swing.JLabel();
        jScrollPane10 = new javax.swing.JScrollPane();
        jTable10 = new javax.swing.JTable();
        jLabel63 = new javax.swing.JLabel();
        jLabel64 = new javax.swing.JLabel();
        jLabel65 = new javax.swing.JLabel();
        eventsP = new javax.swing.JPanel();
        jLayeredPane3 = new javax.swing.JLayeredPane();
        jPanel8 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        dashboardB.setFont(new java.awt.Font("Century", 1, 24)); // NOI18N
        dashboardB.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        dashboardB.setText("DASHBOARD");
        dashboardB.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 255)));
        dashboardB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dashboardBMouseClicked(evt);
            }
        });
        jPanel2.add(dashboardB, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 223, 54));

        studentListB.setFont(new java.awt.Font("Century", 1, 24)); // NOI18N
        studentListB.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        studentListB.setText("STUDENT LIST");
        studentListB.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 255)));
        studentListB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                studentListBMouseClicked(evt);
            }
        });
        jPanel2.add(studentListB, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 223, 51));

        departmentB.setFont(new java.awt.Font("Century", 1, 24)); // NOI18N
        departmentB.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        departmentB.setText("DEPEARTMENT");
        departmentB.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 255)));
        departmentB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                departmentBMouseClicked(evt);
            }
        });
        jPanel2.add(departmentB, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, 223, 52));

        eventsB.setFont(new java.awt.Font("Century", 1, 24)); // NOI18N
        eventsB.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        eventsB.setText("EVENTS");
        eventsB.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 255)));
        eventsB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                eventsBMouseClicked(evt);
            }
        });
        jPanel2.add(eventsB, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 480, 223, 54));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 260, 680));

        BlankP.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        dashboardP.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Century", 1, 48)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("DASHBOARD");
        dashboardP.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 200, 610, 250));

        studentListP.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(102, 102, 102));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setBackground(new java.awt.Color(65, 65, 65));
        jLabel11.setFont(new java.awt.Font("Century", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("STUDENT LIST");
        jLabel11.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(0, 0, 0))); // NOI18N
        jPanel3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 1070, 43));

        jTable1.setBackground(new java.awt.Color(153, 153, 153, 99));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "I.D", "Name", "Course", "Year Lv", "Time-In", "Time-Out", "Events"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 1070, 550));

        jLabel13.setFont(new java.awt.Font("Century", 1, 12)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("EDIT");
        jLabel13.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 255)));
        jPanel3.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 640, 73, 27));

        jLabel14.setFont(new java.awt.Font("Century", 1, 12)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("REMOVE");
        jLabel14.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 255)));
        jPanel3.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 640, 73, 27));

        jLabel15.setFont(new java.awt.Font("Century", 1, 12)); // NOI18N
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("ADD");
        jLabel15.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 255)));
        jPanel3.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 640, 73, 27));

        jLabel16.setFont(new java.awt.Font("Century", 1, 12)); // NOI18N
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("SAVE");
        jLabel16.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 255)));
        jPanel3.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(1002, 638, 73, 27));

        jLabel17.setFont(new java.awt.Font("Century", 1, 12)); // NOI18N
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("APPLY");
        jLabel17.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 255)));
        jPanel3.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(917, 638, 73, 27));

        jLabel18.setFont(new java.awt.Font("Century", 1, 12)); // NOI18N
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("RESET");
        jLabel18.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 255)));
        jPanel3.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 640, 73, 27));

        studentListP.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 2, 1090, 680));

        departmentP.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(51, 51, 51));

        jTextField1.setText("Search here ...");
        jTextField1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField1FocusGained(evt);
            }
        });
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication1/icon/SEArch (2).png"))); // NOI18N

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/menu.png"))); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 1022, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        departmentP.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1090, 60));

        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ccsB.setFont(new java.awt.Font("Century", 1, 18)); // NOI18N
        ccsB.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ccsB.setText("CCS");
        ccsB.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 255)));
        jPanel5.add(ccsB, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, 90, 30));

        cbaaB.setFont(new java.awt.Font("Century", 1, 18)); // NOI18N
        cbaaB.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cbaaB.setText("CBAA");
        cbaaB.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 255)));
        jPanel5.add(cbaaB, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 20, 90, 30));

        claB.setFont(new java.awt.Font("Century", 1, 18)); // NOI18N
        claB.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        claB.setText("CLA");
        claB.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 255)));
        jPanel5.add(claB, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 20, 90, 30));

        ccjeB.setFont(new java.awt.Font("Century", 1, 18)); // NOI18N
        ccjeB.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ccjeB.setText("CCJE");
        ccjeB.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 255)));
        jPanel5.add(ccjeB, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 20, 90, 30));

        cnmB.setFont(new java.awt.Font("Century", 1, 18)); // NOI18N
        cnmB.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cnmB.setText("CNM");
        cnmB.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 255)));
        jPanel5.add(cnmB, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 20, 90, 30));

        tetdB.setFont(new java.awt.Font("Century", 1, 18)); // NOI18N
        tetdB.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tetdB.setText("TETD");
        tetdB.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 255)));
        jPanel5.add(tetdB, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 20, 90, 30));

        cedB.setFont(new java.awt.Font("Century", 1, 18)); // NOI18N
        cedB.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cedB.setText("CED");
        cedB.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 255)));
        jPanel5.add(cedB, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 20, 90, 30));

        hsB.setFont(new java.awt.Font("Century", 1, 18)); // NOI18N
        hsB.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        hsB.setText("HS");
        hsB.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 255)));
        jPanel5.add(hsB, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 20, 90, 30));

        departmentP.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 1090, 70));

        jLayeredPane2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        blank2P.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jLayeredPane2.add(blank2P, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1090, 550));

        ccsP.setBackground(new java.awt.Color(102, 102, 102, 99));
        ccsP.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel33.setBackground(new java.awt.Color(65, 65, 65));
        jLabel33.setFont(new java.awt.Font("Century", 1, 18)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(255, 255, 255));
        jLabel33.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel33.setText("DEPARTMENT FILTER");
        jLabel33.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(0, 0, 0))); // NOI18N
        ccsP.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 6, 1060, 43));

        jTable3.setBackground(new java.awt.Color(153, 153, 153, 99));
        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "I.D", "Name", "Course", "Year Lv", "Time-In", "Time-Out", "Events"
            }
        ));
        jScrollPane3.setViewportView(jTable3);

        ccsP.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 55, 1060, 388));

        jLabel36.setFont(new java.awt.Font("Century", 1, 12)); // NOI18N
        jLabel36.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel36.setText("CHANGE FILTER");
        jLabel36.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 255)));
        ccsP.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 510, 122, 27));

        jLabel37.setFont(new java.awt.Font("Century", 1, 12)); // NOI18N
        jLabel37.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel37.setText("SAVE");
        jLabel37.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 255)));
        ccsP.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 510, 73, 27));

        jLabel38.setFont(new java.awt.Font("Century", 1, 12)); // NOI18N
        jLabel38.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel38.setText("APPLY");
        jLabel38.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 255)));
        ccsP.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 510, 73, 27));

        jLayeredPane2.add(ccsP, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1090, 550));

        cbaaP.setBackground(new java.awt.Color(102, 102, 102, 99));
        cbaaP.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel34.setBackground(new java.awt.Color(65, 65, 65));
        jLabel34.setFont(new java.awt.Font("Century", 1, 18)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(255, 255, 255));
        jLabel34.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel34.setText("DEPARTMENT FILTER");
        jLabel34.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(0, 0, 0))); // NOI18N
        cbaaP.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 6, 1060, 43));

        jTable4.setBackground(new java.awt.Color(153, 153, 153, 99));
        jTable4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "I.D", "Name", "Course", "Year Lv", "Time-In", "Time-Out", "Events"
            }
        ));
        jScrollPane4.setViewportView(jTable4);

        cbaaP.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 55, 1060, 388));

        jLabel40.setFont(new java.awt.Font("Century", 1, 12)); // NOI18N
        jLabel40.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel40.setText("CHANGE FILTER");
        jLabel40.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 255)));
        cbaaP.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 460, 122, 27));

        jLabel41.setFont(new java.awt.Font("Century", 1, 12)); // NOI18N
        jLabel41.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel41.setText("SAVE");
        jLabel41.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 255)));
        cbaaP.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 510, 73, 27));

        jLabel42.setFont(new java.awt.Font("Century", 1, 12)); // NOI18N
        jLabel42.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel42.setText("APPLY");
        jLabel42.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 255)));
        cbaaP.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 510, 73, 27));

        jLayeredPane2.add(cbaaP, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1090, 550));

        claP.setBackground(new java.awt.Color(102, 102, 102, 99));
        claP.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel35.setBackground(new java.awt.Color(65, 65, 65));
        jLabel35.setFont(new java.awt.Font("Century", 1, 18)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(255, 255, 255));
        jLabel35.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel35.setText("DEPARTMENT FILTER");
        jLabel35.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(0, 0, 0))); // NOI18N
        claP.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 6, 1060, 43));

        jTable5.setBackground(new java.awt.Color(153, 153, 153, 99));
        jTable5.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "I.D", "Name", "Course", "Year Lv", "Time-In", "Time-Out", "Events"
            }
        ));
        jScrollPane5.setViewportView(jTable5);

        claP.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 55, 1060, 388));

        jLabel43.setFont(new java.awt.Font("Century", 1, 12)); // NOI18N
        jLabel43.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel43.setText("CHANGE FILTER");
        jLabel43.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 255)));
        claP.add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 460, 122, 27));

        jLabel44.setFont(new java.awt.Font("Century", 1, 12)); // NOI18N
        jLabel44.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel44.setText("SAVE");
        jLabel44.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 255)));
        claP.add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 490, 73, 27));

        jLabel45.setFont(new java.awt.Font("Century", 1, 12)); // NOI18N
        jLabel45.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel45.setText("APPLY");
        jLabel45.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 255)));
        claP.add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 490, 73, 27));

        jLayeredPane2.add(claP, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1090, 550));

        ccjeP.setBackground(new java.awt.Color(102, 102, 102, 99));
        ccjeP.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel46.setBackground(new java.awt.Color(65, 65, 65));
        jLabel46.setFont(new java.awt.Font("Century", 1, 18)); // NOI18N
        jLabel46.setForeground(new java.awt.Color(255, 255, 255));
        jLabel46.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel46.setText("DEPARTMENT FILTER");
        jLabel46.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(0, 0, 0))); // NOI18N
        ccjeP.add(jLabel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 6, 1060, 43));

        jTable6.setBackground(new java.awt.Color(153, 153, 153, 99));
        jTable6.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "I.D", "Name", "Course", "Year Lv", "Time-In", "Time-Out", "Events"
            }
        ));
        jScrollPane6.setViewportView(jTable6);

        ccjeP.add(jScrollPane6, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 55, 1060, 388));

        jLabel47.setFont(new java.awt.Font("Century", 1, 12)); // NOI18N
        jLabel47.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel47.setText("CHANGE FILTER");
        jLabel47.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 255)));
        ccjeP.add(jLabel47, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 490, 122, 27));

        jLabel48.setFont(new java.awt.Font("Century", 1, 12)); // NOI18N
        jLabel48.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel48.setText("SAVE");
        jLabel48.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 255)));
        ccjeP.add(jLabel48, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 490, 73, 27));

        jLabel49.setFont(new java.awt.Font("Century", 1, 12)); // NOI18N
        jLabel49.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel49.setText("APPLY");
        jLabel49.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 255)));
        ccjeP.add(jLabel49, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 490, 73, 27));

        jLayeredPane2.add(ccjeP, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1090, 550));

        cnmP.setBackground(new java.awt.Color(102, 102, 102, 99));
        cnmP.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel50.setBackground(new java.awt.Color(65, 65, 65));
        jLabel50.setFont(new java.awt.Font("Century", 1, 18)); // NOI18N
        jLabel50.setForeground(new java.awt.Color(255, 255, 255));
        jLabel50.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel50.setText("DEPARTMENT FILTER");
        jLabel50.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(0, 0, 0))); // NOI18N
        cnmP.add(jLabel50, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 6, 1060, 43));

        jTable7.setBackground(new java.awt.Color(153, 153, 153, 99));
        jTable7.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "I.D", "Name", "Course", "Year Lv", "Time-In", "Time-Out", "Events"
            }
        ));
        jScrollPane7.setViewportView(jTable7);

        cnmP.add(jScrollPane7, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 55, 1060, 388));

        jLabel51.setFont(new java.awt.Font("Century", 1, 12)); // NOI18N
        jLabel51.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel51.setText("CHANGE FILTER");
        jLabel51.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 255)));
        cnmP.add(jLabel51, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 510, 122, 27));

        jLabel52.setFont(new java.awt.Font("Century", 1, 12)); // NOI18N
        jLabel52.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel52.setText("SAVE");
        jLabel52.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 255)));
        cnmP.add(jLabel52, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 510, 73, 27));

        jLabel53.setFont(new java.awt.Font("Century", 1, 12)); // NOI18N
        jLabel53.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel53.setText("APPLY");
        jLabel53.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 255)));
        cnmP.add(jLabel53, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 510, 73, 27));

        jLayeredPane2.add(cnmP, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1090, 550));

        tetdP.setBackground(new java.awt.Color(102, 102, 102, 99));
        tetdP.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel54.setBackground(new java.awt.Color(65, 65, 65));
        jLabel54.setFont(new java.awt.Font("Century", 1, 18)); // NOI18N
        jLabel54.setForeground(new java.awt.Color(255, 255, 255));
        jLabel54.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel54.setText("DEPARTMENT FILTER");
        jLabel54.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(0, 0, 0))); // NOI18N
        tetdP.add(jLabel54, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 6, 1060, 43));

        jTable8.setBackground(new java.awt.Color(153, 153, 153, 99));
        jTable8.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "I.D", "Name", "Course", "Year Lv", "Time-In", "Time-Out", "Events"
            }
        ));
        jScrollPane8.setViewportView(jTable8);

        tetdP.add(jScrollPane8, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 55, 1060, 388));

        jLabel55.setFont(new java.awt.Font("Century", 1, 12)); // NOI18N
        jLabel55.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel55.setText("CHANGE FILTER");
        jLabel55.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 255)));
        tetdP.add(jLabel55, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 510, 122, 27));

        jLabel56.setFont(new java.awt.Font("Century", 1, 12)); // NOI18N
        jLabel56.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel56.setText("SAVE");
        jLabel56.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 255)));
        tetdP.add(jLabel56, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 510, 73, 27));

        jLabel57.setFont(new java.awt.Font("Century", 1, 12)); // NOI18N
        jLabel57.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel57.setText("APPLY");
        jLabel57.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 255)));
        tetdP.add(jLabel57, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 510, 73, 27));

        jLayeredPane2.add(tetdP, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1090, 550));

        cedP.setBackground(new java.awt.Color(102, 102, 102, 99));
        cedP.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel58.setBackground(new java.awt.Color(65, 65, 65));
        jLabel58.setFont(new java.awt.Font("Century", 1, 18)); // NOI18N
        jLabel58.setForeground(new java.awt.Color(255, 255, 255));
        jLabel58.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel58.setText("DEPARTMENT FILTER");
        jLabel58.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(0, 0, 0))); // NOI18N
        cedP.add(jLabel58, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 6, 1060, 43));

        jTable9.setBackground(new java.awt.Color(153, 153, 153, 99));
        jTable9.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "I.D", "Name", "Course", "Year Lv", "Time-In", "Time-Out", "Events"
            }
        ));
        jScrollPane9.setViewportView(jTable9);

        cedP.add(jScrollPane9, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 55, 1060, 388));

        jLabel59.setFont(new java.awt.Font("Century", 1, 12)); // NOI18N
        jLabel59.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel59.setText("CHANGE FILTER");
        jLabel59.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 255)));
        cedP.add(jLabel59, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 510, 122, 27));

        jLabel60.setFont(new java.awt.Font("Century", 1, 12)); // NOI18N
        jLabel60.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel60.setText("SAVE");
        jLabel60.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 255)));
        cedP.add(jLabel60, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 510, 73, 27));

        jLabel61.setFont(new java.awt.Font("Century", 1, 12)); // NOI18N
        jLabel61.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel61.setText("APPLY");
        jLabel61.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 255)));
        cedP.add(jLabel61, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 510, 73, 27));

        jLayeredPane2.add(cedP, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1090, 550));

        hsP.setBackground(new java.awt.Color(102, 102, 102, 99));
        hsP.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel62.setBackground(new java.awt.Color(65, 65, 65));
        jLabel62.setFont(new java.awt.Font("Century", 1, 18)); // NOI18N
        jLabel62.setForeground(new java.awt.Color(255, 255, 255));
        jLabel62.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel62.setText("DEPARTMENT FILTER");
        jLabel62.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(0, 0, 0))); // NOI18N
        hsP.add(jLabel62, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 6, 1060, 43));

        jTable10.setBackground(new java.awt.Color(153, 153, 153, 99));
        jTable10.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "I.D", "Name", "Course", "Year Lv", "Time-In", "Time-Out", "Events"
            }
        ));
        jScrollPane10.setViewportView(jTable10);

        hsP.add(jScrollPane10, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 55, 1060, 388));

        jLabel63.setFont(new java.awt.Font("Century", 1, 12)); // NOI18N
        jLabel63.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel63.setText("CHANGE FILTER");
        jLabel63.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 255)));
        hsP.add(jLabel63, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 510, 122, 27));

        jLabel64.setFont(new java.awt.Font("Century", 1, 12)); // NOI18N
        jLabel64.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel64.setText("SAVE");
        jLabel64.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 255)));
        hsP.add(jLabel64, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 510, 73, 27));

        jLabel65.setFont(new java.awt.Font("Century", 1, 12)); // NOI18N
        jLabel65.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel65.setText("APPLY");
        jLabel65.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 255)));
        hsP.add(jLabel65, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 510, 73, 27));

        jLayeredPane2.add(hsP, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1090, 550));

        departmentP.add(jLayeredPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 1090, 550));

        eventsP.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLayeredPane3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1090, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 680, Short.MAX_VALUE)
        );

        jLayeredPane3.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1090, 680));

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1090, Short.MAX_VALUE)
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 680, Short.MAX_VALUE)
        );

        jLayeredPane3.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1090, 680));

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1090, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 680, Short.MAX_VALUE)
        );

        jLayeredPane3.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1090, 680));

        eventsP.add(jLayeredPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1090, 680));

        jLayeredPane1.setLayer(BlankP, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(dashboardP, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(studentListP, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(departmentP, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(eventsP, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BlankP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(dashboardP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(studentListP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(departmentP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(eventsP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BlankP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(dashboardP, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(studentListP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(departmentP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(eventsP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jLayeredPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 0, 1090, 680));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1350, 680));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void studentListBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_studentListBMouseClicked
        // TODO add your handling code here:
        studentListB.removeAll();
        studentListB.add(studentListP);
        studentListB.repaint();
        studentListB.revalidate();
    }//GEN-LAST:event_studentListBMouseClicked

    private void departmentBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_departmentBMouseClicked
        // TODO add your handling code here:
        departmentB.removeAll();
        departmentB.add(departmentP);
        departmentB.repaint();
        departmentB.revalidate();
       
    }//GEN-LAST:event_departmentBMouseClicked

    private void eventsBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eventsBMouseClicked
        // TODO add your handling code here:
        eventsB.removeAll();
        eventsB.add(eventsP);
        eventsB.repaint();
        eventsB.revalidate();
       
        
    }//GEN-LAST:event_eventsBMouseClicked

    private void dashboardBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dashboardBMouseClicked
        // TODO add your handling code here:
        dashboardB.removeAll();
        dashboardB.add(dashboardP);
        dashboardB.repaint();
        dashboardB.revalidate();
      
    }//GEN-LAST:event_dashboardBMouseClicked

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField1FocusGained
        // TODO add your handling code here:
       
    }//GEN-LAST:event_jTextField1FocusGained

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admin_View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admin_View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admin_View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admin_View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        try {
            UIManager.setLookAndFeel(new FlatVuesionIJTheme());
        } catch (UnsupportedLookAndFeelException ex) {
            System.err.println("Failed to initialize LaF");
        }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Admin_View().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BlankP;
    private javax.swing.JPanel blank2P;
    private javax.swing.JLabel cbaaB;
    private javax.swing.JPanel cbaaP;
    private javax.swing.JLabel ccjeB;
    private javax.swing.JPanel ccjeP;
    private javax.swing.JLabel ccsB;
    private javax.swing.JPanel ccsP;
    private javax.swing.JLabel cedB;
    private javax.swing.JPanel cedP;
    private javax.swing.JLabel claB;
    private javax.swing.JPanel claP;
    private javax.swing.JLabel cnmB;
    private javax.swing.JPanel cnmP;
    private javax.swing.JLabel dashboardB;
    private javax.swing.JPanel dashboardP;
    private javax.swing.JLabel departmentB;
    private javax.swing.JPanel departmentP;
    private javax.swing.JLabel eventsB;
    private javax.swing.JPanel eventsP;
    private javax.swing.JLabel hsB;
    private javax.swing.JPanel hsP;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JLabel jLabel64;
    private javax.swing.JLabel jLabel65;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLayeredPane jLayeredPane2;
    private javax.swing.JLayeredPane jLayeredPane3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable10;
    private javax.swing.JTable jTable3;
    private javax.swing.JTable jTable4;
    private javax.swing.JTable jTable5;
    private javax.swing.JTable jTable6;
    private javax.swing.JTable jTable7;
    private javax.swing.JTable jTable8;
    private javax.swing.JTable jTable9;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel studentListB;
    private javax.swing.JPanel studentListP;
    private javax.swing.JLabel tetdB;
    private javax.swing.JPanel tetdP;
    // End of variables declaration//GEN-END:variables
}
